remove "test report" github action
anyway, it fails because of some authorization issue:
> HTTPError: Response code 400 (Authentication information is not given in the correct format. Check the value of Authorization header.)